version: '3.8'

services:
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    container_name: go-restfull-staging
    ports:
      - "8000:8000"
    volumes:
      # Uncomment to use external config file
      # - ./custom.yml:/app/config.yml
      # - ./custom.yml:/configs/user.yml
    environment:
      - ENV=staging
      - TZ=Asia/Jakarta
      # Uncomment to use external config via environment variable
      # - CONFIG_PATH=/configs/user.yml
    depends_on:
      - postgres
      - redis
    networks:
      - go-restfull-network
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: go-restfull-postgres-staging
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-restfull-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: go-restfull-redis-staging
    ports:
      - "6379:6379"
    networks:
      - go-restfull-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: go-restfull-minio-staging
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":8900"
    volumes:
      - minio_data:/data
    networks:
      - go-restfull-network
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: go-restfull-mailpit-staging
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - go-restfull-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  go-restfull-network:
    driver: bridge 