version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: go-restfull-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/tmp
      # Uncomment to use external config file
      # - ./custom.yml:/app/config.yml
      # - ./custom.yml:/configs/user.yml
    environment:
      - ENV=development
      - TZ=Asia/Jakarta
      # Uncomment to use external config via environment variable
      # - CONFIG_PATH=/configs/user.yml
    depends_on:
      - postgres
      - redis
    networks:
      - go-restfull-network

  postgres:
    image: postgres:17
    container_name: go-restfull-postgres-dev
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-restfull-network

  redis:
    image: redis:alpine
    container_name: go-restfull-redis-dev
    ports:
      - "6379:6379"
    networks:
      - go-restfull-network

  minio:
    image: minio/minio:latest
    container_name: go-restfull-minio-dev
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":8900"
    volumes:
      - minio_data:/data
    networks:
      - go-restfull-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: go-restfull-mailpit-dev
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - go-restfull-network

volumes:
  postgres_data:
  minio_data:

networks:
  go-restfull-network:
    driver: bridge 