services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: on-failure
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - .:/app:delegated
    environment:
      APP_ENV: "development"
    ports:
        - 8000:8000
    networks:
      - webapi


  postgres:
    image: postgres:17
    restart: on-failure
    volumes:
      - ./db_data/postgresql:/var/lib/postgresql/data
    environment:
      PGPASSWORD: 'secret'
      POSTGRES_DB: 'my_db'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "my_db", "-U", "my_user"]
      retries: 3
      timeout: 5s
    networks:
      - webapi

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - ./db_data/redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - webapi
  
  waha:
    restart: always
    container_name: waha
    image: devlikeapro/waha:latest
    # image: devlikeapro/waha-plus:latest
    ports:
      - '3000:3000/tcp'
    volumes:
      - './.sessions:/app/.sessions'
      - './.media:/app/.media'
    environment:
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_PRINT_QR=False
      - WAHA_MEDIA_STORAGE=LOCAL
      - WHATSAPP_FILES_LIFETIME=0
      - WHATSAPP_FILES_FOLDER=/app/.media
    networks:
      - webapi


  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - './db_data/minio:/data'
    command: 'minio server /data --console-address ":8900"'
    healthcheck:
      test: [ CMD, mc, ready, local ]
      retries: 3
      timeout: 5s
    networks:
      - webapi
  
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./db_data/mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - webapi

networks:
  webapi:
    driver: bridge
