services:
  postgres:
    image: postgres:17
    restart: on-failure
    volumes:
      - ./db_data/postgresql:/var/lib/postgresql/data
    environment:
      PGPASSWORD: 'secret'
      POSTGRES_DB: 'my_db'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - 'my_db'
        - '-U'
        - 'my_user'
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - ./db_data/redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
  # Uncomment this section if you want to use mongo
  # mongo:
  #   image: mongo:6.0.4-jammy
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo_user
  #     MONGO_INITDB_ROOT_PASSWORD: mongo_password
