env: "dev" # dev, staging, production
app:
  key: "my-app-key"
  name: "My App"
  nameSlug: "my-app"
  jwtSecret: "your-super-secret-jwt-key-here-make-it-long-and-secure"
  accessTokenExpiration: 24

httpServer:
  port: 8000

log:
  level: "debug"
  stacktraceLevel: "error" # debug, info, warn, error, dpanic, panic, fatal
  fileEnabled: false
  fileSize: 10 # MB
  filePath: "log/log.log"
  fileCompress: false # enable log file compress before rotate
  maxAge: 1 # days to keep log files
  maxBackups: 10 # umber of log files

postgres:
  host: "postgres" # use "host.docker.internal" if you run app inside docker container
  port: 5432
  database: "my_db"
  schema: "public"
  username: "my_user"
  password: "secret"
  maxConnections: 20
  maxIdleConnections: 10

Redis:
  - host: "redis"
    port: 6379
    password: ""
    db: 0

minio:
  enable: false
  endpoint: '127.0.0.1:9000'
  accessKeyID: 'minioadmin'
  secretAccessKey: 'minioadmin'
  useSSL: false
  bucket: 'my-bucket'


sentry:
  dsn: ""
  environment: "DEV"
  release: "webapi@v0.1.0"
  debug: false


scheduler:
  timezone: "Asia/Jakarta" # Timezone for cron jobs
# schedules:
#   - cron: "0 */20 * * * *"
#     job: "SyncAll"

email:
  smtpHost: "smtp.gmail.com"
  smtpPort: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  fromAddress: "noreply@yourapp.com"
  fromName: "Your App"
