env: "test"
app:
  key: "test-app-key"
  name: "Test App"
  nameSlug: "test-app"
  jwtSecret: "test-jwt-secret-key-for-testing-purposes-only"

httpServer:
  port: 8000

log:
  level: "debug"
  stacktraceLevel: "error"
  fileEnabled: false
  fileSize: 10
  filePath: "log/log.log"
  fileCompress: false
  maxAge: 1
  maxBackups: 10

postgres:
  host: "localhost"
  port: 5432
  database: "test_db"
  schema: "public"
  username: "test_user"
  password: "test_password"
  maxConnections: 20
  maxIdleConnections: 10

Redis:
  - host: "localhost"
    port: 6379
    password: ""
    db: 0

minio:
  enable: false
  endpoint: '127.0.0.1:9000'
  accessKeyID: 'minioadmin'
  secretAccessKey: 'minioadmin'
  useSSL: false
  bucket: 'test-bucket'

sentry:
  dsn: ""
  environment: "TEST"
  release: "webapi@v0.1.0"
  debug: false

email:
  smtpHost: "smtp.gmail.com"
  smtpPort: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  fromAddress: "noreply@yourapp.com"
  fromName: "Your App"
  
scheduler:
  timezone: "UTC"
# schedules:
#   - cron: "0 */20 * * * *"
#     job: "SyncAll"
